# Generated by Django 5.2.11 on 2026-02-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price1',
            field=models.FloatField(blank=True, default=None),
        ),
    ]
