# Generated by Django 5.2.11 on 2026-02-28 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0002_book_price1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='price1',
        ),
    ]
